server:
  port: 8090

spring:
  application:
    name: user
  cloud:
    nacos:
      server-addr: 39.101.72.163:8848 # nacos地址,不要动

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: Aa123456.

  redis:
    host: 127.0.0.1
    port: 6379


