server:
  port: 10010
spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB  # 开启文件上传
  cloud:
    nacos:
      server-addr: 39.101.72.163:8848 # nacos地址
    gateway:
      routes:
        - id: user # 路由标示，必须唯一，建议直接用模块名
          uri: lb://user # 路由的目标地址,lb://+模块名字
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 整个模块内所有接口的URL格式（一个模块内的URL格式应该统一）

        - id: StockData # 路由标示，必须唯一，建议直接用模块名
          uri: lb://StockData # 路由的目标地址,lb://+模块名字
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/StockData/** # 整个模块内所有接口的URL格式（一个模块内的URL格式应该统一）

        - id: PythonConnection # 路由标示，必须唯一，建议直接用模块名
          uri: lb://PythonConnection # 路由的目标地址,lb://+模块名字
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/PythonConnection/** # 整个模块内所有接口的URL格式（一个模块内的URL格式应该统一）

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST